version: '3.8'

services:
  api-gateway:
    image: golang:1.18-alpine
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
    networks:
      - ecommerce-network

  inventory-service:
    image: golang:1.18-alpine
    container_name: inventory-service
    build:
      context: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - ecommerce-network

  order-service:
    image: golang:1.18-alpine
    container_name: order-service
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - ecommerce-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
